# 範例
***

# [教學目標]

* 能夠使用不同的方法初始化一個陣列
* 知道固定大小對於陣列的意義
* 了解不同的亂數陣列有什麼差異



In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
1.17.2


In [2]:
# 內建型態做轉換

import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# 會自動轉換成範圍比較大的型態：

print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：

print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


In [4]:
# 字典型態被轉成陣列不符合期待

print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

# 正確的寫法應該寫轉成有序的 List 再作轉換

print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

{0: 123, 1: 456}
1
[[  0 123]
 [  1 456]]
4


In [5]:
# 從固定大小的初始值開始

print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 9))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [6]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 從固定大小的序列值開始

print(np.arange( 10, 30, 5 ))
print(np.linspace( 0, 2, 3 ))
print(np.logspace( 0, 2, 3 ))


[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]


In [8]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 1.50804913  0.36184618]
 [-0.19310674  2.8500345 ]
 [ 0.55085171 -0.55189352]]
[[0.94585825 0.98237174]
 [0.02059556 0.07463031]
 [0.65095139 0.1257261 ]]
[[1 9]
 [8 8]
 [2 6]]


In [9]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-1.48694842  0.00986209 -0.69841623]
 [ 0.57149085  0.23251928 -0.52627692]]
[[0.127169   0.25986264]
 [0.12060637 0.4878208 ]
 [0.47287624 0.395855  ]]
[[8 5]
 [2 3]
 [8 1]]
