# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

print('type of list(a)[0]: ', type(list(a)[0]))
print('type of tolist()[0]: ', type(a.tolist()[0]))

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
type of list(a)[0]:  <class 'numpy.ndarray'>
type of tolist()[0]:  <class 'list'>


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
a = np.random.randint(10, size=6) 

print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('length: ', len(a))
print('type: ', type(a))

[6 2 8 2 4 6]
ndim:  1
shape:  (6,)
size:  6
dtype:  int64
itemsize:  8
length:  6
type:  <class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('length: ', len(b))
print('type: ', type(b))

[[7 7 4 7]
 [9 5 7 5]
 [0 1 8 3]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int64
itemsize:  8
length:  3
type:  <class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('length: ', len(c))
print('type: ', type(c))

[[[2 8]
  [3 0]
  [6 8]]

 [[2 8]
  [8 6]
  [3 3]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int64
itemsize:  8
length:  2
type:  <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[9, 0, 6, 3, 3, 4]
[9, 0, 6, 3, 3, 4]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[6, 2, 1, 0], [0, 3, 1, 2], [6, 9, 1, 4]]
[array([6, 2, 1, 0]), array([0, 3, 1, 2]), array([6, 9, 1, 4])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 7], [1, 0], [2, 2]], [[9, 4], [8, 1], [5, 5]]]
[array([[3, 7],
       [1, 0],
       [2, 2]]), array([[9, 4],
       [8, 1],
       [5, 5]])]


In [8]:
def tolist(iterable):
    return [tolist(obj) for obj in iterable] if type(iterable) == np.ndarray else iterable

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 0, 6, 3, 3, 4]
[[6, 2, 1, 0], [0, 3, 1, 2], [6, 9, 1, 4]]
[[[3, 7], [1, 0], [2, 2]], [[9, 4], [8, 1], [5, 5]]]
