# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


### 答：

`np.zeros((2, 3))` 會產生 2*3 且值皆為 0 的 array

`np.empty((2, 3))` 會產生 2*3 且元素未初始化的 array

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
import numpy as np

In [2]:
# 參考解答

a = np.random.rand(2, 3)
print(a)

from numpy.random import default_rng
rng = default_rng()

a = rng.integers(0, 10, size=(2, 3)) 
print(a)

[[0.39034046 0.04776911 0.1754116 ]
 [0.44535517 0.60287259 0.11524004]]
[[9 2 3]
 [1 2 6]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40

a = rng.integers(m, n, size=(2, 3)) 
print(a)

[[23 38 28]
 [30 31 21]]
