# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
import numpy as np

In [2]:
arr = np.arange(11) + 1
for idx, a in enumerate(arr):
    if(a >= 3 and a <= 6):
        arr[idx] = a * -1
        
print(arr)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [4]:
A = np.random.rand(3, 6)
print(A)

B = A[A>0.5]
print(B)
print(B.size)

[[0.32918225 0.30210069 0.13118727 0.39825098 0.16955603 0.59941571]
 [0.04138074 0.24089851 0.36589631 0.54107732 0.44375854 0.55989942]
 [0.24168187 0.71388789 0.70080901 0.44219554 0.74774858 0.06836161]]
[0.59941571 0.54107732 0.55989942 0.71388789 0.70080901 0.74774858]
6
