# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
import numpy as np

In [2]:
arr = np.arange(11) + 1

# for idx, a in enumerate(arr):
#     if(a >= 3 and a <= 6):
#         arr[idx] = a * -1

arr[(arr >= 3) & (arr <= 6)] *= -1
        
print(arr)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [3]:
A = np.random.rand(3, 6)
print(A)

B = A[A>0.5]
print(B)
print(B.size)

[[0.44268576 0.87381705 0.54887438 0.70447695 0.89145122 0.83774248]
 [0.74577088 0.92671504 0.25008426 0.75743395 0.72018555 0.34022838]
 [0.64989746 0.20891054 0.46099035 0.4463873  0.09033283 0.02061032]]
[0.87381705 0.54887438 0.70447695 0.89145122 0.83774248 0.74577088
 0.92671504 0.75743395 0.72018555 0.64989746]
10
