# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
'''
Your Code
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
import numpy as np

In [3]:
A = np.random.random((5, 5))

A = (A - A.min()) / (A.max() - A.min())
A

array([[0.62858584, 0.45364789, 0.68039831, 0.89913971, 0.30988325],
       [0.85238072, 0.07657624, 0.50128746, 0.21002764, 0.90938534],
       [0.34074453, 0.01897771, 0.34268501, 0.33879919, 0.13477407],
       [0.77928993, 1.        , 0.75360221, 0.38966265, 0.71506139],
       [0.77405375, 0.92762406, 0.1390966 , 0.        , 0.47178105]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [4]:
a = np.round(np.random.random(10)*100)
print(a)

print('a.argmax(): ', a.argmax())
a[a.argmax()] = -1
print(a)

[92. 81. 63. 95. 56. 62. 63. 10. 79. 80.]
a.argmax():  3
[92. 81. 63. -1. 56. 62. 63. 10. 79. 80.]
