# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
1.17.2


In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[6 1 2 ... 7 9 6]
  [1 2 8 ... 0 8 0]
  [7 0 0 ... 0 1 1]
  ...
  [7 0 2 ... 1 8 9]
  [6 8 0 ... 8 9 3]
  [1 9 9 ... 5 9 1]]

 [[2 0 9 ... 9 3 1]
  [3 3 5 ... 9 7 2]
  [4 6 5 ... 9 2 3]
  ...
  [7 2 7 ... 4 2 5]
  [4 6 4 ... 9 2 6]
  [3 4 2 ... 9 3 5]]

 [[0 2 8 ... 1 9 3]
  [3 3 7 ... 8 0 8]
  [5 6 1 ... 8 2 8]
  ...
  [2 0 6 ... 9 4 0]
  [6 4 0 ... 5 8 9]
  [5 9 4 ... 5 7 7]]

 ...

 [[7 8 3 ... 1 6 9]
  [1 6 7 ... 6 1 0]
  [0 0 4 ... 0 0 7]
  ...
  [5 5 5 ... 8 1 1]
  [6 6 5 ... 0 7 8]
  [0 4 0 ... 6 8 9]]

 [[4 4 2 ... 2 7 0]
  [4 0 1 ... 7 0 7]
  [3 5 0 ... 0 4 7]
  ...
  [1 5 7 ... 3 2 0]
  [9 7 1 ... 3 6 4]
  [0 7 7 ... 6 7 9]]

 [[0 0 8 ... 3 0 9]
  [8 1 4 ... 8 7 1]
  [4 3 1 ... 0 8 6]
  ...
  [1 4 2 ... 8 7 2]
  [6 0 8 ... 4 8 2]
  [4 7 3 ... 7 5 4]]]


In [3]:
%timeit -n 10 a = 2

for i in Z:
    for j in i:
        for k in j:
            i = i + 1

57.1 ns ± 23 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit -n 10 a = 2

for i in Z.flat:
    i = i+1

47.3 ns ± 20.1 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i = i+1

78.3 ns ± 22.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [6]:

Z = np.random.randint(0,10,50)
print(Z)


[9 6 7 0 0 5 7 1 1 3 1 7 8 4 5 7 8 9 7 9 4 4 1 3 8 6 7 2 7 0 6 5 1 6 1 9 3
 9 0 3 9 2 1 6 4 2 6 5 4 9]


In [7]:
rint = (np.bincount(Z).argmax())
rint

1

In [8]:
np.where(Z == rint)[0]

array([ 7,  8, 10, 22, 32, 34, 42])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [9]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[2, 1, 1, 1, 4, 1]
[2, 1, 1, 1, 4, 1]
[[0, 6, 5, 5], [0, 1, 9, 6], [3, 0, 6, 9]]
[array([0, 6, 5, 5]), array([0, 1, 9, 6]), array([3, 0, 6, 9])]
[[[2, 2], [4, 1], [4, 0]], [[5, 6], [1, 9], [4, 8]]]
[array([[2, 2],
       [4, 1],
       [4, 0]]), array([[5, 6],
       [1, 9],
       [4, 8]])]


In [10]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[2, 1, 1, 1, 4, 1]
[[0, 6, 5, 5], [0, 1, 9, 6], [3, 0, 6, 9]]
[[[2, 2], [4, 1], [4, 0]], [[5, 6], [1, 9], [4, 8]]]
